# Generated by Django 2.0.3 on 2018-04-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('register_date', models.DateField()),
                ('password', models.CharField(max_length=45)),
                ('ban', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'registered_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('register_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('register_date', models.CharField(blank=True, max_length=45, null=True)),
                ('password', models.CharField(max_length=45)),
                ('admin_id', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('register_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.IntegerField()),
                ('username', models.CharField(max_length=45)),
                ('register_date', models.CharField(max_length=45)),
                ('agent_id', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'agent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BanList',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ban_length', models.CharField(blank=True, max_length=45, null=True)),
                ('time_remaining', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'ban_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('approval', models.IntegerField()),
                ('status', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAuthority',
            fields=[
                ('role_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_authority',
                'managed': False,
            },
        ),
    ]
