# Generated by Django 2.0.3 on 2018-05-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180404_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
